Import('env')

local_env = env.Clone()

env.Install(env['PROJECT_BIN_PATH'], 'sample_data')

data_source_test = env.Program(target = 'data_source_test', source = ['data_source_test.cpp'], LIBS = ['snapshot', 'exception', 'ssl'])
env.Install(env['PROJECT_BIN_PATH'], data_source_test)

append_store_read = env.Program(target = 'append_store_read', source = ['append_store_read.cpp'], LIBS = env['PROJ_LIBS'] + env['LOG_LIBS'] + env['QFS_LIBS'] + env['BASIC_LIBS'])
env.Install(env['PROJECT_BIN_PATH'], append_store_read)
