Import('*')
local_env = env.Clone()
#env = Environment()
local_env.Program(target = "data_source_test", source = ["dedup_types.cpp", "snapshot_types.cpp", "data_source.cpp", "data_source_test.cpp", "exception.cpp"], LIBS=["stdc++", "ssl"])
