Import('env')

local_env = env.Clone()
local_env.Append(CCFLAGS = '-std=c++0x')

snapshot = local_env.StaticLibrary(target = 'snapshot', source = ['trace_types.cpp', 'snapshot_types.cpp', 'snapshot_control.cpp', 'data_source.cpp', 'dirty_bit.cpp', 'cds_cache.cpp', 'cds_index.cpp', 'cds_data.cpp', 'bloom_filter_functions.cpp'])
local_env.Install(local_env['PROJECT_LIB_PATH'], snapshot)

snapshot_write = local_env.Program(target = 'snapshot_write', source = ['snapshot_write.cpp'], LIBS = env['PROJ_LIBS'] + env['QFS_LIBS'] + env['LOG_LIBS'] + env['CACHE_LIBS'] + env['BASIC_LIBS'])
local_env.Install(local_env['PROJECT_BIN_PATH'], snapshot_write)

prog = local_env.Program(target = 'snapshot_read', source = ['snapshot_read.cpp'], LIBS = env['PROJ_LIBS'] + env['QFS_LIBS'] + env['LOG_LIBS'] + env['CACHE_LIBS'] + env['BASIC_LIBS'])
local_env.Install(local_env['PROJECT_BIN_PATH'], prog)

cds_loader = local_env.Program(target = 'cds_loader', source = ['cds_loader.cpp'], LIBS = env['PROJ_LIBS'] + env['QFS_LIBS'] + env['LOG_LIBS'] + env['CACHE_LIBS'] + env['BASIC_LIBS'])
local_env.Install(local_env['PROJECT_BIN_PATH'], cds_loader)

bf_test = local_env.Program(target = 'bf_test', source = ['bloom_filter_test.cpp'], LIBS = env['PROJ_LIBS'] + env['LOG_LIBS'] + env['BASIC_LIBS'])
local_env.Install(local_env['PROJECT_BIN_PATH'], bf_test)

prog = local_env.Program(target = 'cds_verify', source = ['cds_verify.cpp'], LIBS = env['PROJ_LIBS'] + env['LOG_LIBS'] + env['CACHE_LIBS'] + env['BASIC_LIBS'])
local_env.Install(local_env['PROJECT_BIN_PATH'], prog)
