# -*- mode: python -*-
Import('env')
env = env.Clone()

env.Cangjie('append_store_cj.h', 'append_store.cj')

lib_append_store_a = env.StaticLibrary('append_store', Glob('*.cpp'))
Default(lib_append_store_a)

env.SConscript('test/SConscript', exports='env')
env.SConscript('tool/SConscript', exports='env')


