Import('env')

local_env = env.Clone()

if local_env['PROJ_MODE'] == 'debug':
    local_env.InstallAs(local_env['PROJECT_BIN_PATH'] + '/Log4cxxConfig.xml', 'Log4cxxConfig.debug.xml')
else:
    local_env.InstallAs(local_env['PROJECT_BIN_PATH'] + '/Log4cxxConfig.xml', 'Log4cxxConfig.release.xml')
