env = Environment()
env.Program(target='bar', source=['qfs_file_helper.cpp', 'qfs_file_system_helper.cpp'])
	# header= ['file_system_helper.h', 'file_helper.h', 'qfs_file_system_helper.h', 'qfs_file_helper.h'])
# file_helper.h  file_system_helper.h  qfs_file_helper.cpp  qfs_file_system_helper.cpp  SConstruct

