Import('env')

local_env = env.Clone()

hash_distribution = local_env.Program(target = 'hash_distribution', source = ['hash_distribution.cpp'], LIBS = env['PROJ_LIBS'] + env['BASIC_LIBS'] + env['LOG_LIBS'])
local_env.Install(local_env['PROJECT_BIN_PATH'], hash_distribution)

local_env.Install(local_env['PROJECT_BIN_PATH'], 'memcached_start.sh')
local_env.Install(local_env['PROJECT_BIN_PATH'], 'memcached_stop.sh')
local_env.Install(local_env['PROJECT_BIN_PATH'], 'metaserver_start.sh')
local_env.Install(local_env['PROJECT_BIN_PATH'], 'chunkserver_start.sh')
